[package]
name = "network_common"
version = "0.1.0"
edition = "2024"

[lib]

[dependencies]
serde = { workspace = true }
anyhow = { workspace = true }
ml-dsa = { workspace = true }
blake3 = { workspace = true }
